function renderAnalytics(){
  const selected=window.analyticsProduct||'all';
  const catalog=JSON.parse(localStorage.getItem('velora-products')||'[]');
  const visible=selected==='all'?catalog:catalog.filter(p=>String(p.id)===selected);
  const revenue=visible.reduce((sum,p)=>sum+Number(p.price||0)*({1:120,2:86,3:64}[p.id]||12),0);
  const cost=Math.round(revenue*.5),profit=revenue-cost;
  openDynamic('Analytics',{actions:`<select class="gold-button" id="analyticsRange"><option>All products</option><option>This month</option><option>This year</option></select><select class="gold-button" id="analyticsProduct"><option value="all">All products</option>${catalog.map(p=>`<option value="${p.id}" ${String(p.id)===selected?'selected':''}>${p.name}</option>`).join('')}</select>`,content:`<div class="analytics-grid"><div class="analytics-card"><span>Total revenue</span><strong>$${revenue.toLocaleString()}</strong><em>+18.4%</em><div class="bars">${[35,48,42,70,58,78,65,92,75,100].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div><div class="analytics-card"><span>Total product cost</span><strong>$${cost.toLocaleString()}</strong><em>Operating cost</em><div class="bars blue">${[45,55,38,70,62,78,54,85,72,96].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div><div class="analytics-card"><span>Net profit</span><strong>$${profit.toLocaleString()}</strong><em>+22.1%</em><div class="bars green">${[30,42,55,44,60,52,75,68,86,94].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div></div><div class="analytics-panel"><h3>Product profitability</h3><div class="profit-table"><div class="profit-head"><span>Product</span><span>Sold</span><span>Cost</span><span>Revenue</span><span>Profit</span><span>Margin</span></div>${visible.map(p=>{const sold={1:120,2:86,3:64}[p.id]||12,rev=Number(p.price)*sold,c=Math.round(rev*.5),pr=rev-c;return `<div class="profit-row"><div><strong>${p.name}</strong><small>${p.category}${p.vip?' · VIP':''}</small></div><span>${sold}</span><span>$${c.toLocaleString()}</span><span>$${rev.toLocaleString()}</span><strong class="profit-number">$${pr.toLocaleString()}</strong><span class="margin-number">50%</span></div>`}).join('')||'<p class="empty-comments">No products available.</p>'}</div></div>`});
  document.getElementById('analyticsProduct').addEventListener('change',e=>{window.analyticsProduct=e.target.value;renderAnalytics()});
}
