const roleParams=new URLSearchParams(location.search);
const routeView=roleParams.get('view');
const routePath=location.pathname.toLowerCase();
const entryRole=routeView==='admin'||routePath.endsWith('/admin.html')?'admin':'customer';
const accountRole=entryRole;
localStorage.setItem('velora-account-role',accountRole);
function addRoleActions(){const profile=document.getElementById('profileView');if(!profile||document.getElementById('customerViewLink'))return;const button=document.createElement('button');button.id='customerViewLink';button.className='secondary-action';button.textContent=accountRole==='customer'?'Open admin dashboard':'Open customer view';button.onclick=()=>{const next=accountRole==='customer'?'admin.html':'store.html';localStorage.setItem('velora-account-role',accountRole==='customer'?'admin':'customer');window.location.assign(new URL(next,window.location.href).href)};profile.appendChild(button)}
function renderCustomerWishlist(){const ids=JSON.parse(localStorage.getItem('velora-wishlist')||'[]'),saved=products.filter(p=>ids.includes(p.id));dashboardSections.forEach(el=>el.style.display='none');dynamicPage.hidden=false;openDynamic('Wishlist',{actions:'',content:`<div class="wishlist-grid">${saved.map(p=>`<article class="wishlist-card"><img src="${p.images?.[0]||p.image}" alt="${p.name}"><div><small>${p.category||'Velora product'}</small><h3>${p.name}</h3><strong>$${Number(p.price||0).toLocaleString()}</strong><div><button class="gold-button" data-wish-view="${p.id}">View product</button><button class="secondary-action" data-wish-remove="${p.id}">Remove</button></div></div></article>`).join('')||'<div class="customer-empty-page"><span class="eyebrow">VELORA CUSTOMER AREA</span><h2>Wishlist</h2><p>Your saved products will appear here.</p></div>'}</div>`});document.querySelectorAll('[data-wish-view]').forEach(b=>b.onclick=()=>openProductDetails(Number(b.dataset.wishView)));document.querySelectorAll('[data-wish-remove]').forEach(b=>b.onclick=()=>{localStorage.setItem('velora-wishlist',JSON.stringify(ids.filter(id=>id!==Number(b.dataset.wishRemove))));renderCustomerWishlist()})}
function setupCustomerMode(){document.body.classList.add('customer-mode');const nav=document.querySelector('.nav-list');if(!nav)return;nav.innerHTML='<button class="nav-item active" data-customer-section="Store"><span class="icon">▦</span>Store</button><button class="nav-item" data-customer-section="Orders"><span class="icon">♧</span>My orders</button><button class="nav-item" data-customer-section="VIP"><span class="icon">✦</span>VIP collection</button><button class="nav-item" data-customer-section="Wishlist"><span class="icon">☆</span>Wishlist</button><button class="nav-item" data-customer-section="Reviews"><span class="icon">◇</span>My reviews</button><button class="nav-item" data-customer-section="Account"><span class="icon">⚙</span>Account</button>';document.querySelector('.welcome h1').textContent='Welcome to Velora';document.getElementById('subtitle').textContent='Discover pieces styled for every detail.';/* Navigation is delegated by customer-navigation-fix.js after all customer features load. Keeping a second listener here caused clicks to compete and made the page appear frozen. */addRoleActions()}
if(accountRole==='customer')setupCustomerMode();else addRoleActions();
